SocialGouv/gitlab-ci-yml

base_deploy_nodejs_chart_stage.yml
---
**BREAKING CHANGES**: feat(nodejs_chart): force the wildcard-crt if not in production
- **.base_deploy_nodejs_chart_stage**: The job is now forcing `--set ingress.tls[0].secretName=wildcard-crt` if not in production mode.
=> feat(nodejs_chart): force the wildcard-crt if not in production

autodevops_simple_app.yml
---
In production, the namespace should be the name of the startup
=> ci(autodevops): remove the gitlab project id on the generated namespace

base_deploy_app_chart_stage.yml
---
**BREAKING CHANGE : Update socialgouv/app github release tag to v6.0.0**  
A `PORT` variable is now required
Before
```yaml
Deploy myapp:
extends:
- .base_deploy_app_chart_stage
variables:
CONTEXT: app
VALUES_FILE: ./.k8s/app.values.yml
```
After
```yaml
Deploy myapp:
extends:
- .base_deploy_app_chart_stage
variables:
PORT: 8080
CONTEXT: app
VALUES_FILE: ./.k8s/app.values.yml
```
see https://github.com/SocialGouv/helm-charts/releases/tag/v6.0.0
=> feat(deps)!: update socialgouv/app github release tag to v6.0.0

base_azure_db_stage.yml
This enable pgcrypto extension when `ENABLE_AZURE_POSTGRES=1`, which is mandatory for hasura
=> feat(azure-db): add pgcrypto

base_deploy_app_chart_stage.yml
---
BREAKING CHANGE: **app_chart** do not override set production values
As we use the production ready values in `values.socialgouv.yaml` of https://github.com/SocialGouv/helm-charts/tree/v6.0.0/charts/app, we only need to override the render when not in production
=> fix(app)!: do not override set production values

autodevops_simple_app.yml, base_azure_db_stage.yml, base_create_namespace_stage.yml, base_delete_useless_k8s_ns_stage.yml, base_delete_useless_managed_postgresql_stage.yml
---
We remove the environment name entries in the job templates.
This helps reusing the `base_*` job templates
BREAKING CHANGE: **feat(autodevops)!: centralize environment in autodevops file**
Our autodevops now drives the environment info.
```diff
Azure db stage:
extends: .base_azure_db_stage
+  environment:
+    name: ${CI_COMMIT_REF_NAME}-dev
Drop azure db:
extends: .base_drop_azure_db
+  environment:
+    name: ${CI_COMMIT_REF_NAME}-dev
Create namespace stage:
extends: .base_create_namespace_stage
+  environment:
+    name: ${CI_COMMIT_REF_NAME}-dev
Delete useless k8s ns stage:
extends: .base_delete_useless_k8s_ns_stage
+  environment:
+    name: ${CI_COMMIT_REF_NAME}-dev
Delete useless managed postgresql:
extends: .base_delete_useless_managed_postgresql_stage
+  environment:
+ …
```
=> feat(autodevops)!: centralize environment in autodevops file

README.md, autodevops_simple_app.yml
---
One can now extends existing autodevops jobs
**Before**
```yaml
include:
- project: SocialGouv/gitlab-ci-yml
file: /autodevops_simple_app.yml
ref: v14.0.0
variables:
PORT: 8080
VALUES_FILE: ./.k8s.app.values.yml
Build:
extends:
- .base_yarn_build_next
dependencies:
- Install
needs:
- Install
variables:
VERSION: ${CI_COMMIT_SHORT_SHA}
MY_API_URL: "%%MY_API_URL%%"
script:
- yarn build
- yarn export
artifacts:
expire_in: 1 day
paths:
- out
```
**After**
```yaml
include:
- project: SocialGouv/gitlab-ci-yml
file: /autodevops_simple_app.yml
ref: v14.0.0
variables:
PORT: 8080
VALUES_FILE: ./.k8s.app.values.yml
Build:
extends:
- .autodevops_build
variables:
VERSION: ${CI_COMMIT_SHORT_SHA}
MY_API_URL: "%%MY_API_URL%%"
script:
- yarn next build
- yarn next export
artifacts:
expire_in: 1 day …
```
=> feat(autodevops)!: allow existing jobs extend

CHANGELOG.md, README.md, autodevops_simple_app.yml
---
BREAKING CHANGE: review branches will no longer be prefixed
=> revert: remove review/ prefix on env name

base_trivy_scan.yml
As `$ trivy IMAGE_NAME` is deprecated 
see https://github.com/SocialGouv/docker/pull/265
=> feat(trivy): use image subcommand

base_trivy_scan.yml
looks like `cache_dir` is a global option while others are related to the `image` command
```sh
NAME:
trivy - A simple and comprehensive vulnerability scanner for containers
USAGE:
trivy [global options] command [command options] image_name
VERSION:
0.8.0
COMMANDS:
image, i   scan an image
client, c  client mode
server, s  server mode
help, h    Shows a list of commands or help for one command
GLOBAL OPTIONS:
--quiet, -q        suppress progress bar and log output (default: false) [$TRIVY_QUIET]
--debug, -d        debug mode (default: false) [$TRIVY_DEBUG]
--cache-dir value  cache directory (default: "/root/.cache/trivy") [$TRIVY_CACHE_DIR]
--help, -h         show help (default: false)
--version, -v      print the version (default: false)
```
=> fix(trivy): change arguments order

base_notify_github_stage.yml
Dont stop pipeline when notifications fails. This can happen when the GH branch is deleted before the branch pipeline fully executed
=> fix(notify): allow_failure

CHANGELOG.md, README.md, base_deploy_kosko_stage.yml
https://media.giphy.com/media/J2UgSh9ElRKz8Aswj0/giphy.gif width=100%>
---
BREAKING CHANGE: might break `kubectl apply` on the output manifest if `KUBE_NAMESPACE` is not set on the GitLab job
=> feat(kosko)!: remove envsubst on appended yaml

base_deploy_kosko_stage.yml
As we now have a testing process for kosko-charts, I would argue that we know have a clear difference between what we need to _deploy_ and what we need to _test_. If we want to fix a testing framework for kosko-charts testing, we should ensure that we do not install dev dependencies when deploying.
BREAKING CHANGE: You will want to move your dependencies in the "dependencies" of your `package.json`
```diff
"dependencies": {
"@kosko/env": "^0.5.2",
"@socialgouv/kosko-charts": "^4.0.0-alpha.8",
"@socialgouv/kosko-charts": "^4.0.0-alpha.8",
-    "kubernetes-models": "^0.8.1"
+    "kubernetes-models": "^0.8.1",
+    "kosko": "^0.9.2",
+    "ts-node": "^9.0.0",
+    "typescript": "^4.0.5"
},
"devDependencies": {
"@babel/core": "^7.12.9",
"@babel/plugin-transform-modules-commonjs": "^7.12.1",
- …
```
=> feat(kosko): only install production deps when deploying

base_deploy_kosko_stage.yml
Job fail when there is no manifest.yaml to print the deployed hosts
balot
https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-admin/-/jobs/1169970
=> fix(deploy): ensure manifest.yaml exist to print

base_deploy_kosko_stage.yml
when the url is too long and the YAML line-wrapped, the urls are not displayed.
this PR use yq so we can extract the exact url from the YAML properly
needs docker/no-k8s:4.9.0
=> fix(deploy): fix urls print when too long

base_autodevops.yml, base_trigger_stage.yml
---
**BREAKING CHANGE**: Manual releases will need to go through the `TRIGGER` env variable now
No impact on existing `Trigger Production` and `Trigger Release` jobs.
But other jobs will need to do `TRIGGER="<my stuff>"`
=> feat(autodevops)!: use generic TRIGGER

autodevops.yml
I dont think we have any reason to re-run the master pipeline on `chore(release):` commits, do we ?
=> fix(autodevops): skip post-release master pipeline

base_semantic_release_stage.yml
---
Correct Github remote errors when releasing from GitLab to GitHub repository.
As we are switching from direct cloning of GitHub repository hierarchy to GitLab sub groups per startup, we can't use the `CI_PROJECT_PATH` anymore to guess the GitHub repo to push too has it contains the GitLab subgroup that doesn't exit on Github resulting on the "classic" error : 
```sh
Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/SocialGouv/archifiltre/archifiltre-statistics.git
remote: Not Found
```
The alternative could be using the `CI_PROJECT_ROOT_NAMESPACE` and `CI_PROJECT_TITLE` to reconstituate the GitHub flat repository hierarchy 
see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
=> feat(semantic_release): ignore subgroup on release github remote

base_autodevops.yml
set a 3 days expiration for dev ens, 1 day is a bit short
=> fix(autodevops): increase envs lifetime

base_deploy_kosko_stage.yml
Hack to allow legacy gitlab pipelines to use the new cert-manager annotation
=> fix(base_deploy_kosko_stage): force new cert-manager annotation
