SocialGouv/gitlab-ci-yml

- .gitlab-ci.yml
- .releaserc.yml
- README.md
- base_sementic_release_stage.yml
> feat: add semantic release stage

- base_register_stage.yml
> feat(register): improve register code

- autodevops_simple_app.yml
> fix(autodevops): wrong production var check

- base_deploy_hpa_chart_stage.yml
- base_deploy_nodejs_chart_stage.yml
---
Following #32
BREAKING CHANGE: update SocialGouv/helm-charts to v3.0.0
See https://github.com/SocialGouv/helm-charts/releases/tag/v3.0.0
> feat(deps)!: update SocialGouv/helm-charts to v3.0.0

- .gitlab-ci.yml
> ci(gitlab): add SocialGouv/sample-next-app master test

- base_deploy_hpa_chart_stage.yml
- base_deploy_nodejs_chart_stage.yml
- base_docker_helm_image_stage.yml
This reverts commit 097b187ce96f6fb43a807dd29dc5fb0db7a355c6.
As it fails the master build
> Revert "feat(helm): install helm just and socialgouv repo by default(#37)"

- .gitlab-ci.yml
- autodevops_simple_app.yml
- base_create_namespace_stage.yml
- base_deploy_nodejs_chart_stage.yml
- base_docker_helm_image_stage.yml
- base_docker_kubectl_image_stage.yml
- base_notify_github_stage.yml
- base_register_stage.yml
- base_yarn_stage.yml
> ci(gitlab)!: make it gitlab.com compatible

- README.md
- base_deploy_nodejs_chart_stage.yml
> feat(nodejs): allow user HELM_RENDER_ARGS

- base_create_namespace_stage.yml
> feat(namespaces): prefer using global variables

- base_deploy_hpa_chart_stage.yml
- base_deploy_nodejs_chart_stage.yml
> feat(hpa): prefer using global variables

- autodevops_simple_app.yml
> fix(autodevops): ensure that prod deploy has PRODUCTION set

- README.md
- autodevops_simple_app.yml
- base_delete_useless_k8s_ns_stage.yml
> fix(delete): update default namespace filter

- README.md
- autodevops_simple_app.yml
when using socialgouv autodevops the `ENABLE_AZURE_POSTGRES` flag can create a dedicated db on PG azure
Todo : 
- prod deploy
> feat(autodevops)!: add PG deployment with ENABLE_AZURE_POSTGRES

- README.md
- autodevops_simple_app.yml
- base_migrate_azure_db.yml
---
**BREAKING CHANGES**: move manual azure db migration to a separate base
You now need to include the base migrate to have the `Migrate Azure DB (dev)` set
```yml
include:
- project: SocialGouv/gitlab-ci-yml
file: /base_migrate_azure_db.yml
ref: v8.0.0
```
> refactor(autodevops)!: move manual azure db migration to a separate base

- autodevops_simple_app.yml
- base_yarn_stage.yml
> feat(autodevops): aggresive install-build-register speed

- autodevops_simple_app.yml
- base_azure_db_stage.yml
> feat(autodevops): get pg admin cred from k8s secret

- base_deploy_hpa_chart_stage.yml
- base_deploy_nodejs_chart_stage.yml
---
BREAKING CHANGE: update to socialgouv/helm-chats@4.0.1
- see https://github.com/SocialGouv/helm-charts/blob/master/CHANGELOG.md#400-2020-03-03
> feat(charts)!: update to socialgouv/helm-chats@4.0.1

- base_create_namespace_stage.yml
> fix(create_namespace): remove extra )

- base_yarn_stage.yml
> fix(yarn): remove extra stage, image

- README.md
- autodevops_simple_app.yml
as per gitlab : https://docs.gitlab.com/ee/topics/autodevops/#disable-jobs
> feat(autodevops): make lint and test jobs optional

- base_azure_db_stage.yml
@revolunet it should look like this...
> WIP base_managed_pg.yml base_create_db_user

- README.md
- autodevops_simple_app.yml
> feat: add NOTIFY_DISABLED variable

- base_deploy_app_chart_stage.yml
---
Might be a breaking change :thinking:
> feat(deploy-app)!: force set certificate from $CONTEXT

- base_deploy_app_chart_stage.yml
> fix(deploy-app): move HELM_RENDER_ARGS at end of the render cmd

- README.md
- base_notify_mattermost.yml
NB: We have an issue on our mattermost ATM that prevent us from modifying the avatar and username (config cannot be saved for some reason). but it works
> feat: add mattermost notification base job

- base_azure_db_stage.yml
> feat(azure-db): enable hstore extension

- base_yarn_stage.yml
> ci(gitlab): only cache yarn by default

- README.md
- base_trivy_scan.yml
> feat: add trivy job

- base_deploy_app_chart_stage.yml
> feat(deploy_app_chart): archive the manifest

- autodevops_simple_app.yml
- base_azure_db_stage.yml
Autodevops : Add an automatic DB cleanup in dev environments
related to https://github.com/SocialGouv/docker/pull/259
> feat(autodevops): auto cleanup azure dbs

- base_azure_db_stage.yml
one may want to use `base_azure_db` without getting admin secrets
> fix(azure_db): dont always extract secrets

- base_azure_db_stage.yml
we want to make sure we have enough commits in history
> fix(azure-db): increase GIT_DEPTH when cleanning up the db

- base_azure_db_stage.yml
We need to pull all remote branches to be able to check commit in remote branches too
> fix(azure-db): pull all branches

- autodevops_simple_app.yml
> fix(azure-db): dont autoclean

- base_autodevops.yml
we should do this only for renovate... but in the meantime...
> fix(review): set env expiration back to 1 day

- base_deploy_kosko_stage.yml
make it easier to to find deployed env url
> feat(deploy): bigger deploy url in gitlab logs

- base_deploy_kosko_stage.yml
https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/jobs/1029100
> fix(kosko): fix foiroose print

- .gitlab-ci.yml
- base_semantic_release_stage.yml
- base_yarn_stage.yml
Reverts SocialGouv/gitlab-ci-yml#411
> Revert "feat(deps): update node docker tag to v15.0.1"

- base_deploy_kosko_stage.yml
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FiE4lKpKqwe7QIQCPjG%2Fgiphy.gif&token=again" data-gitmeme-token="again"><img src="https://media2.giphy.com/media/iE4lKpKqwe7QIQCPjG/giphy.gif" title="Created by gitme.me with /again"/></a>
> fix(kosko): rererefix env debug

- README.md
- base_nuclei_scan.yml
Add a basic nuclei scan base job with all default templates (363 rules atm). ex: https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/jobs/1112637
> feat: add base_nuclei_scan.yml

- base_autodevops.yml
- base_deploy_kosko_stage.yml
> feat(kosko): share env with the user

- base_deploy_kosko_stage.yml
> fix(kosko): yet another url print

- base_autodevops.yml
> fix(autodevops): dont run test+lint on tags

- base_autodevops.yml
Auto trigger release only on master, alpha, beta
> fix(autodevops): dont always trigger release

- base_deploy_kosko_stage.yml
could be better with yq but should work most of the time :)
> fix: handle multiple hosts urls fix #429

- base_register_stage.yml
This reverts commit f16afc0d4dd044e5746796a6efc1782cf893e639.
> Revert "feat(deps): update docker docker tag to v20"

- base_autodevops.yml
C'est pour supprimer celui-ci :
> fix(autodevops): dont trigger release when released

- README.md
- autodevops.yml
- base_autodevops.yml
- base_register_docker_stage.yml
- base_register_kaniko_stage.yml
BREAKING CHANGE: The file `base_kaniko_stage.yml` no longer exists.
> feat: Switch from Docker to Kaniko based on pipeline env variable: AUTO_DEVOPS_KANIKO.

- base_deploy_kosko_stage.yml
Me again about printing looong urls :) #RunningGag
> fix(yq): yq version 4 args

- base_register_kaniko_stage.yml
as in base_register_docker_stage
> fix(base_register_kaniko_stage): add default stage

- base_autodevops.yml
> fix(autodevops): autodevops_stop_review is not using an image with kapp

- base_autodevops.yml
> feat(autodevops)!: disable auto deploy on branches to save budget

- base_deploy_kosko_stage.yml
---
\from https://carvel.dev/kapp/docs/latest/dangerous-flags/#--dangerous-override-ownership-of-existing-resources
> feat(kosko): add dangerous-override-ownership-of-existing-resources flag to kapp

- base_deploy_kosko_stage.yml
> feat: add rancher/grafana urls

- base_deploy_kosko_stage.yml
This will show ALL rules on ALL ingress instead of the first one only.
> fix(kosko-deploy): output multiple rules url

- autodevops.yml
- base_deploy_kosko_stage.yml
addd pods and workloads grafana dashboard links
> feat: add grafana urls
